### ISSUE TITLE
TextSimilaritySpace issue UserWarning on CUDA initialization

### ISSUE THREAD

**Issue by jhk753** [superlinked/superlinked#43]
**Describe the bug**
TextSimilaritySpace function returns user warning if no Cuda driver available on the machine. 
`python3.10/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 803: system has unsupported display driver / cuda driver combination (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0`

**To Reproduce**
Just follow the boiler plate notebook https://github.com/superlinked/superlinked/blob/main/notebook/semantic_search_news.ipynb and you should get the warning when running TextSimilaritySpace in cell 10

**Expected behavior**
Either the function can't run without cuda driver (and no GPU) and you should probably make that clear in the requirements, or it can and then why issue a warning?

**System**
 - Version: [e.g. 3.10.0]
 - List of package installed on the codeenv used: 
 `altair==5.2.0
annotated-types==0.6.0
attrs==23.2.0
backcall==0.2.0
beartype==0.17.2
certifi==2024.2.2
charset-normalizer==3.3.2
click==8.1.7
comm==0.2.2
decorator==5.1.1
filelock==3.13.1
fsspec==2024.3.1
furl==2.1.3
huggingface-hub==0.21.4
idna==3.6
ipykernel==4.8.2
ipython==7.34.0
ipython-genutils==0.2.0
ipywidgets==8.1.2
jedi==0.19.1
Jinja2==3.1.3
joblib==1.3.2
jsonschema==4.21.1
jsonschema-specifications==2023.12.1
jupyter-client==6.1.12
jupyter_core==4.12.0
jupyterlab_widgets==3.0.10
MarkupSafe==2.1.5
matplotlib-inline==0.1.6
mpmath==1.3.0
networkx==3.2.1
nltk==3.8.1
numpy==1.22.4
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.4.99
nvidia-nvtx-cu12==12.1.105
orderedmultidict==1.0.1
packaging==24.0
pandas==2.2.1
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
pillow==10.2.0
prompt-toolkit==3.0.43
ptyprocess==0.7.0
pydantic==2.6.4
pydantic_core==2.16.3
Pygments==2.17.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
pyzmq==23.2.1
referencing==0.34.0
regex==2023.12.25
requests==2.31.0
rpds-py==0.18.0
safetensors==0.4.2
scikit-learn==1.4.1.post1
scipy==1.12.0
sentence-transformers==2.2.2
sentencepiece==0.2.0
simplegeneric==0.8.1
six==1.16.0
superlinked==3.10.0
sympy==1.12
threadpoolctl==3.4.0
tokenizers==0.15.2
toolz==0.12.1
torch==2.2.1
torchvision==0.17.1
tornado==6.1
tqdm==4.66.2
traitlets==5.1.1
transformers==4.39.0
triton==2.2.0
typing_extensions==4.10.0
tzdata==2024.1
urllib3==2.2.1
wcwidth==0.2.13
widgetsnbextension==4.0.10`

**Comment by svonava** [comment]
Did the code actually run correctly or you couldn't get it to run?

The warning could make sense because of speed considerations - it's useful to realize that a CPU fall back has been triggered if you are running on a GPU-enabled kernel and you were hoping for a speedup.

**Comment by ClaireSuperlinked** [comment]
@jhk753 just wanted to check in here and if you were able to get the code to run?

**Comment by ClaireSuperlinked** [comment]
@kembala was there a solution on this? Could we replicate the issue or can this be closed?

**Comment by kembala** [comment]
> @kembala was there a solution on this? Could we replicate the issue or can this be closed?

To be able to replicate I would need more information on what notebook environment and machine was used.
We are smoke testing these notebooks and by checking it on Google Colab ([here](https://colab.research.google.com/github/superlinked/superlinked/blob/main/notebook/semantic_search_news.ipynb)) it seems to function well within the provided environment. 

Based on a [quick search](https://stackoverflow.com/questions/66371130/cuda-initialization-unexpected-error-from-cudagetdevicecount) this could be some nvidia specific issue connected to the environment it was run at.

@jhk753 can you provide more details on what notebook environment you used for the experiment?

As a quick fix i would suggest to try it out in Google Colab or Jupyter (or locally).

**Comment by ClaireSuperlinked** [comment]
@jhk753 closing this ticket for now but please feel free to reopen if you see the issue agan
