### ISSUE TITLE
`StringList` field containing more than 1 element causing `ValueError` when putting data into the `InMemorySource`

### ISSUE THREAD

**Issue by yassinehamdouni** [superlinked/superlinked#53]
**Describe the bug**
Getting the following error: `ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()` when calling `source_job.put([jobs_df])` (where `source_job` is an `InMemorySource` object, and `jobs_df` is a `DataFrame`)
- seems to be caused by having a `StringList` field in schema(s), and the Lists contain more than 1 element
- issue arises when putting data into the `InMemorySource`

**Location of the error (according to the traceback)**
in the `if key != self._id_name and not pd.isnull(value)`  (specifically the `not pd.isnull(value)` part) operation in the `unmarshal` method (found in `dataframe_parser.py` )

**To Reproduce**
Using your example [here](https://github.com/superlinked/superlinked/blob/main/notebook/recommendations_e_commerce.ipynb) - you should be able to reproduce it by slightly tweaking the example you provided:
1. add a `StringList` field to your schemas (make sure to seed the sample data with **multiple elements** in these StringLists)
2. create a `CategoricalSimilaritySpace` using that field
3. trigger the error by calling `source_product.put([products_df])`

**Expected behavior**
I would expect to be able to include `StringList`s that contain multiple elements in my schemas (ex: user has listed multiple "role types" that they are interested in)

**System**
 - Version: 6.0.0

**Comment by krisztian-gajdar** [comment]
Hi Yassine, thank you for flagging this. This issue has been solved in version 6.0.1.

**Comment by yassinehamdouni** [comment]
Awesome, thank you!
