### ISSUE TITLE
Data Uploaders unexpected behavior

### ISSUE THREAD

**Issue by yassinehamdouni** [superlinked/superlinked#76]
**Describe the bug**
Experencing a couple bugs, when working with Data Uploaders
1. Unable to re-use a data uploader, after initial ingestion.
- was initially able to get the data uploaded to my vector db, using a `jsonl` file (i was able to confirm the data was uploaded to my mongo vector db)
- however, when i triggered the exact same data uploader again (using the same jsonl file), i started getting this error: `MismatchingDimensionException: OnlineAggregationNode` can only process inputs having same length, got 0 (stack trace in 1st screenshot below)
2. Getting a `ValueError` when triggering a different data uploader
- triggering the data uploader using a `jsonl` file, but i keep getting this error: `ValueError: Invalid value 7257 for the given field data type FieldDataType.STRING`
- as you can see in the 2nd screenshot below (i highlighted the relevant part), the system is claiming the `user_id` value of `7257` is not a string. however, if you look at the data, it is in fact a string..
- here is the data record that is causing the error: `{"id":"7257","user_id":"7257","created_at":1604553153,"is_a_cb_fellow":"true","first_name":"Test","last_name":"User","country":"","latitude":-360.0,"longitude":-360.0,"location":"","current_or_desired_role":"Director, Revenue Operations","personal_summary":"","photo_url":"test_photo_url","sectors":["Energy","Materials \u0026 Manufacturing","Transportation","Buildings","Food, Agriculture, \u0026 Land Use"],"categories":["Construction, Architecture \u0026 Crafts","Data, Analytics \u0026 Machine Learning","Operations, Project Management \u0026 Strategy"],"sub_categories":["n/a"],"job_types":["Full time role"],"experience_levels":["Senior Level"],"timezones":[-5.0],"remote_preferences":["Hybrid","Remote"],"org_sizes":["6-10","11-20","21-50","51-100","101-250","251-500","501-1000","1001-5000","5000 +"],"jobseeker_status":"","work_experience":"","work_experience_clone":"","education":"","skills_list":[],"skills_str":"","concatenated_cover_letters":"","personal_summary_clone":"","headline":"","geo_location":[-360.0,-360.0],"is_currently_flagged":"false"}`
- Full stack trace included in 2nd screenshot below

**To Reproduce**
The full specification (the `.py` files + the `.jsonl` files are in [this slack thread](https://climate-careers.slack.com/archives/C07DT5S3RHA/p1728083366300839))

**Expected behavior**
- re: bug 1 above - per [this message](https://climate-careers.slack.com/archives/C07DT5S3RHA/p1724948933821889?thread_ts=1724946375.553489&cid=C07DT5S3RHA) from Andrey, i expect to be able to re-use a data uploader
- re: bug 2 above - i expect the system to recognize the String value and for the data ingestion to proceed successfully 

**System (fill in)**
 - Version: 9.49.0

**Screenshots**
`MismatchingDimensionException: OnlineAggregationNode` error:
![Screenshot 2024-10-04 at 6 48 07 PM](https://github.com/user-attachments/assets/d22a4cea-a385-4b5e-bfb7-dc64a8c7b526)

`ValueError: Invalid value 7257 for the given field data type FieldDataType.STRING` error: 
![Screenshot 2024-10-04 at 7 00 03 PM](https://github.com/user-attachments/assets/b32080e2-17f7-45ad-b291-f731c59392ad)

**Comment by Gui-greg** [comment]
Hello @yassinehamdouni! Thanks for sharing the details! Just to clarify, how long had the system been running between the first successful upload and the error? Also, was the server continuously running during that time, or did it restart or undergo any updates (like a version change) in between? Also, unfortunately I am not part of that Slack channel, can you share the .py and .jsonl files with me on our Slack channel or invite me to yours?

**Comment by yassinehamdouni** [comment]
Hi @Gui-greg ! I don't exactly remember. but the system had been running for a couple hours max, and was not restarted, from what I can recall.

As for the .py and .jsonl files - I just tagged you in Slack, with a link to the message where I included those things.

**Comment by Gui-greg** [comment]
Hi @yassinehamdouni  👋

We've deployed a fix that should address the issues you reported above. Could you please verify if everything is working as expected now? If the problems are resolved, feel free to close this issue.

Thank you for bringing this to our attention!
